MODELS_CONFIG = {
    # Mel Band Roformer
    1000: {
        "model_name": "kimberlyjsn_vocals",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/KimberleyJSN/melbandroformer/resolve/main/MelBandRoformer.ckpt?download=true",
        "conf_url": "https://raw.githubusercontent.com/ZFTurbo/Music-Source-Separation-Training/main/configs/KimberleyJensen/config_vocals_mel_band_roformer_kj.yaml",
    },
    1001: {
        "model_name": "unwa_kim_ft_v1",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Kim-Mel-Band-Roformer-FT/resolve/main/kimmel_unwa_ft.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Kim-Mel-Band-Roformer-FT/resolve/main/config_kimmel_unwa_ft.yaml?download=true",
    },
    1002: {
        "model_name": "unwa_instrumental_v1e",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-Inst/resolve/main/inst_v1e.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-Inst/resolve/main/config_melbandroformer_inst.yaml?download=true",
    },
    1003: {
        "model_name": "unwa_vocals_big_beta_v5e",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-big/resolve/main/big_beta5e.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-big/resolve/main/big_beta5e.yaml?download=true",
    },
    1004: {
        "model_name": "unwa_instvoc_duality_v1",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-InstVoc-Duality/resolve/main/melband_roformer_instvoc_duality_v1.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-InstVoc-Duality/resolve/main/config_melbandroformer_instvoc_duality.yaml?download=true",
    },
    1005: {
        "model_name": "unwa_instvoc_duality_v2",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-InstVoc-Duality/resolve/main/melband_roformer_instvox_duality_v2.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-InstVoc-Duality/resolve/main/config_melbandroformer_instvoc_duality.yaml?download=true",
    },
    1006: {
        "model_name": "unwa_kim_ft_v2",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Kim-Mel-Band-Roformer-FT/resolve/main/kimmel_unwa_ft2.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Kim-Mel-Band-Roformer-FT/resolve/main/config_kimmel_unwa_ft.yaml?download=true",
    },
    1007: {
        "model_name": "unwa_kim_ft_v2_bleedless",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Kim-Mel-Band-Roformer-FT/resolve/main/kimmel_unwa_ft2_bleedless.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Kim-Mel-Band-Roformer-FT/resolve/main/config_kimmel_unwa_ft.yaml?download=true",
    },
    1008: {
        "model_name": "unwa_big_beta_v1",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-big/resolve/main/melband_roformer_big_beta1.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-big/resolve/main/config_melbandroformer_big.yaml?download=true",
    },
    1009: {
        "model_name": "unwa_big_beta_v2",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-big/resolve/main/melband_roformer_big_beta2.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-big/resolve/main/config_melbandroformer_big.yaml?download=true",
    },
    1010: {
        "model_name": "unwa_big_beta_v3",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-big/resolve/main/melband_roformer_big_beta3.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-big/resolve/main/config_melbandroformer_big.yaml?download=true",
    },
    1011: {
        "model_name": "unwa_big_beta_v4",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-big/resolve/main/melband_roformer_big_beta4.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-big/resolve/main/config_melbandroformer_big_beta4.yaml?download=true",
    },
    1012: {
        "model_name": "unwa_big_beta_v6",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-big/resolve/main/big_beta6.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-big/resolve/main/big_beta6.yaml?download=true",
    },
    1013: {
        "model_name": "unwa_instrumental_v1",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-Inst/resolve/main/melband_roformer_inst_v1.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-Inst/resolve/main/config_melbandroformer_inst.yaml?download=true",
    },
    1014: {
        "model_name": "unwa_instrumental_v2",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-Inst/resolve/main/melband_roformer_inst_v2.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-Inst/resolve/main/config_melbandroformer_inst_v2.yaml?download=true",
    },
    1015: {
        "model_name": "unwa_small_v1",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-small/resolve/main/melband_roformer_small_v1.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-small/resolve/main/config_melbandroformer_small.yaml?download=true",
    },
    1016: {
        "model_name": "becruily_instrumental",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/becruily/mel-band-roformer-instrumental/resolve/main/mel_band_roformer_instrumental_becruily.ckpt?download=true",
        "conf_url": "https://huggingface.co/becruily/mel-band-roformer-instrumental/resolve/main/config_instrumental_becruily.yaml?download=true",
    },
    1017: {
        "model_name": "becruily_vocals",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/becruily/mel-band-roformer-vocals/resolve/main/mel_band_roformer_vocals_becruily.ckpt?download=true",
        "conf_url": "https://huggingface.co/becruily/mel-band-roformer-vocals/resolve/main/config_vocals_becruily.yaml?download=true",
    },
    1018: {
        "model_name": "syh99999_syhft_v1",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/SYH99999/MelBandRoformerSYHFT/resolve/main/MelBandRoformerSYHFT.ckpt?download=true",
        "conf_url": "https://huggingface.co/SYH99999/MelBandRoformerSYHFT/resolve/main/config_vocals_mel_band_roformer_ft.yaml?download=true",
    },
    1019: {
        "model_name": "syh99999_syhft_v2",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/SYH99999/MelBandRoformerSYHFTV2/resolve/main/MelBandRoformerSYHFTV2.ckpt?download=true",
        "conf_url": "https://huggingface.co/SYH99999/MelBandRoformerSYHFT/resolve/main/config_vocals_mel_band_roformer_ft.yaml?download=true",
    },
    1020: {
        "model_name": "syh99999_syhft_v2.5",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/SYH99999/MelBandRoformerSYHFTV2.5/resolve/main/MelBandRoformerSYHFTV2.5.ckpt/MelBandRoformerSYHFTV2.5.ckpt?download=true",
        "conf_url": "https://huggingface.co/SYH99999/MelBandRoformerSYHFT/resolve/main/config_vocals_mel_band_roformer_ft.yaml?download=true",
    },
    1021: {
        "model_name": "syh99999_syhft_v3",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/SYH99999/MelBandRoformerSYHFTV3Epsilon/resolve/main/MelBandRoformerSYHFTV3Epsilon.ckpt?download=true",
        "conf_url": "https://huggingface.co/SYH99999/MelBandRoformerSYHFT/resolve/main/config_vocals_mel_band_roformer_ft.yaml?download=true",
    },
    1022: {
        "model_name": "syh99999_big_syhft_v1_fast",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/SYH99999/MelBandRoformerBigSYHFTV1Fast/resolve/main/MelBandRoformerBigSYHFTV1.ckpt?download=true",
        "conf_url": "https://huggingface.co/SYH99999/MelBandRoformerBigSYHFTV1Fast/resolve/main/config.yaml?download=true",
    },
    1023: {
        "model_name": "syh99999_merged_beta_v1",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/SYH99999/MelBandRoformerMergedSYHFTBeta1/resolve/main/merge_syhft.ckpt?download=true",
        "conf_url": "https://huggingface.co/SYH99999/MelBandRoformerSYHFT/resolve/main/config_vocals_mel_band_roformer_ft.yaml?download=true",
    },
    1024: {
        "model_name": "syh99999_syhft_b1",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/SYH99999/MelBandRoformerSYHFTB1/resolve/main/model3.ckpt?download=true",
        "conf_url": "https://huggingface.co/SYH99999/MelBandRoformerSYHFTB1/resolve/main/config.yaml?download=true",
    },
    1025: {
        "model_name": "syh99999_4_stems_ft_large",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/SYH99999/MelBandRoformer4StemFTLarge/resolve/main/MelBandRoformer4StemFTLarge.ckpt?download=true",
        "conf_url": "https://huggingface.co/SYH99999/MelBandRoformer4StemFTLarge/resolve/main/config.yaml?download=true",
    },
    1026: {
        "model_name": "syh99999_4_stems_ft_large_v2",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/SYH99999/MelBandRoformer4StemFTLarge/resolve/main/ver2.ckpt?download=true",
        "conf_url": "https://huggingface.co/SYH99999/MelBandRoformer4StemFTLarge/resolve/main/config.yaml?download=true",
    },
    # Gabox Models
    1100: {
        "model_name": "gaboxr67_instrumental_fv1",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gaboxFv1.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    1101: {
        "model_name": "gaboxr67_instrumental_fv2",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gaboxFv2.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    1102: {
        "model_name": "gaboxr67_instrumental_fv3",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gaboxFv3.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    1103: {
        "model_name": "gaboxr67_instrumental_fv4_noise",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_Fv4Noise.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    1104: {
        "model_name": "gaboxr67_instrumental_fv5",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/INSTV5.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    1105: {
        "model_name": "gaboxr67_instrumental_fv5_noise",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/INSTV5N.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    1106: {
        "model_name": "gaboxr67_instrumental_fv6",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/INSTV6.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    1107: {
        "model_name": "gaboxr67_instrumental_fv6_noise",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/INSTV6N.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    1108: {
        "model_name": "gaboxr67_instrumental_fv7",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/Inst_GaboxV7.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    1109: {
        "model_name": "gaboxr67_instrumental_fv7_noise",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/INSTV7N.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    1110: {
        "model_name": "gaboxr67_instrumental_fv8",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/experimental/INSTV8.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    1111: {
        "model_name": "gaboxr67_instrumental_fv9",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/experimental/INSTV9.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    1112: {
        "model_name": "gaboxr67_instrumental_fv10",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/experimental/INSTV10.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    1130: {
        "model_name": "gaboxr67_instrumental_fvx",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/Inst_GaboxFVX.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    1150: {
        "model_name": "gaboxr67_instrumental_bv1",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gaboxBv1.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    1151: {
        "model_name": "gaboxr67_instrumental_bv2",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gaboxBv2.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    1170: {
        "model_name": "gaboxr67_vocals_fv1",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/vocals/voc_gaboxFv1.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/vocals/voc_gabox.yaml?download=true",
    },
    1171: {
        "model_name": "gaboxr67_vocals_fv2",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/vocals/voc_gaboxFv2.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/vocals/voc_gabox.yaml?download=true",
    },
    1172: {
        "model_name": "gaboxr67_vocals_fv3",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/vocals/voc_Fv3.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/vocals/voc_gabox.yaml?download=true",
    },
    1173: {
        "model_name": "gaboxr67_vocals_fv4",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/vocals/voc_fv4.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/vocals/voc_gabox.yaml?download=true",
    },
    1190: {
        "model_name": "gaboxr67_karaoke_25_02_2025",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/noblebarkrr/all_models_for_mel_band_roformer/resolve/main/gabox_karaoke_25_02_2025.ckpt?download=true",
        "conf_url": "https://huggingface.co/jarredou/aufr33-viperx-karaoke-melroformer-model/resolve/main/config_mel_band_roformer_karaoke.yaml?download=true",
    },
    1191: {
        "model_name": "gaboxr67_karaoke_28_02_2025",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/noblebarkrr/all_models_for_mel_band_roformer/resolve/main/gabox_karaoke_28_02_2025.ckpt?download=true",
        "conf_url": "https://huggingface.co/jarredou/aufr33-viperx-karaoke-melroformer-model/resolve/main/config_mel_band_roformer_karaoke.yaml?download=true",
    },
    1199: {
        "model_name": "gaboxr67_denoise_debleed",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/denoisedebleed.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    # Anvuew Models
    1030: {
        "model_name": "anvuew_dereverb",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/anvuew/dereverb_mel_band_roformer/resolve/main/dereverb_mel_band_roformer_anvuew_sdr_19.1729.ckpt?download=true",
        "conf_url": "https://huggingface.co/anvuew/dereverb_mel_band_roformer/resolve/main/dereverb_mel_band_roformer_anvuew.yaml?download=true",
    },
    1031: {
        "model_name": "anvuew_dereverb_aggressive",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/anvuew/dereverb_mel_band_roformer/resolve/main/dereverb_mel_band_roformer_less_aggressive_anvuew_sdr_18.8050.ckpt?download=true",
        "conf_url": "https://huggingface.co/anvuew/dereverb_mel_band_roformer/resolve/main/dereverb_mel_band_roformer_anvuew.yaml?download=true",
    },
    1032: {
        "model_name": "anvuew_dereverb_mono",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/anvuew/dereverb_mel_band_roformer/resolve/main/dereverb_mel_band_roformer_mono_anvuew_sdr_20.4029.ckpt?download=true",
        "conf_url": "https://huggingface.co/anvuew/dereverb_mel_band_roformer/resolve/main/dereverb_mel_band_roformer_anvuew.yaml?download=true",
    },
    # Sucial Models
    1040: {
        "model_name": "sucial_aspiration",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/Sucial/Aspiration_Mel_Band_Roformer/resolve/main/aspiration_mel_band_roformer_less_aggr_sdr_18.1201.ckpt?download=true",
        "conf_url": "https://huggingface.co/Sucial/Aspiration_Mel_Band_Roformer/resolve/main/config_aspiration_mel_band_roformer.yaml?download=true",
    },
    1041: {
        "model_name": "sucial_dereverb_deecho",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/Sucial/Dereverb-Echo_Mel_Band_Roformer/resolve/main/dereverb-echo_mel_band_roformer_sdr_10.0169.ckpt?download=true",
        "conf_url": "https://huggingface.co/Sucial/Dereverb-Echo_Mel_Band_Roformer/resolve/main/config_dereverb-echo_mel_band_roformer.yaml?download=true",
    },
    1042: {
        "model_name": "sucial_big_dereverb",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/Sucial/Dereverb-Echo_Mel_Band_Roformer/resolve/main/de_big_reverb_mbr_ep_362.ckpt?download=true",
        "conf_url": "https://huggingface.co/Sucial/Dereverb-Echo_Mel_Band_Roformer/resolve/main/config_dereverb_echo_mbr_v2.yaml?download=true",
    },
    1043: {
        "model_name": "sucial_super_big_dereverb",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/Sucial/Dereverb-Echo_Mel_Band_Roformer/resolve/main/de_super_big_reverb_mbr_ep_346.ckpt?download=true",
        "conf_url": "https://huggingface.co/Sucial/Dereverb-Echo_Mel_Band_Roformer/resolve/main/config_dereverb_echo_mbr_v2.yaml?download=true",
    },
    1044: {
        "model_name": "sucial_dereverb_deecho_mbr_fused_v1",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/Sucial/Dereverb-Echo_Mel_Band_Roformer/resolve/main/dereverb_echo_mbr_fused_0.5_v2_0.25_big_0.25_super.ckpt?download=true",
        "conf_url": "https://huggingface.co/Sucial/Dereverb-Echo_Mel_Band_Roformer/resolve/main/config_dereverb_echo_mbr_v2.yaml?download=true",
    },
    1045: {
        "model_name": "sucial_dereverb_deecho_mbr_v2",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/Sucial/Dereverb-Echo_Mel_Band_Roformer/resolve/main/dereverb_echo_mbr_v2_sdr_dry_13.4843.ckpt?download=true",
        "conf_url": "https://huggingface.co/Sucial/Dereverb-Echo_Mel_Band_Roformer/resolve/main/config_dereverb_echo_mbr_v2.yaml?download=true",
    },
    # Aufr33 & ViperX Models
    1050: {
        "model_name": "aufr33_viperx_karaoke",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/jarredou/aufr33-viperx-karaoke-melroformer-model/resolve/main/mel_band_roformer_karaoke_aufr33_viperx_sdr_10.1956.ckpt?download=true",
        "conf_url": "https://huggingface.co/jarredou/aufr33-viperx-karaoke-melroformer-model/resolve/main/config_mel_band_roformer_karaoke.yaml?download=true",
    },
    1051: {
        "model_name": "aufr33_denoise",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/jarredou/aufr33_MelBand_Denoise/resolve/main/denoise_mel_band_roformer_aufr33_aggr_sdr_27.9768.ckpt?download=true",
        "conf_url": "https://huggingface.co/jarredou/aufr33_MelBand_Denoise/resolve/main/model_mel_band_roformer_denoise.yaml?download=true",
    },
    1052: {
        "model_name": "aufr33_denoise_aggressive",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/jarredou/aufr33_MelBand_Denoise/resolve/main/denoise_mel_band_roformer_aufr33_aggr_sdr_27.9768.ckpt?download=true",
        "conf_url": "https://huggingface.co/jarredou/aufr33_MelBand_Denoise/resolve/main/model_mel_band_roformer_denoise.yaml?download=true",
    },
    1053: {
        "model_name": "aufr33_viperx_decrowd",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://github.com/ZFTurbo/Music-Source-Separation-Training/releases/download/v.1.0.4/mel_band_roformer_crowd_aufr33_viperx_sdr_8.7144.ckpt",
        "conf_url": "https://github.com/ZFTurbo/Music-Source-Separation-Training/releases/download/v.1.0.4/model_mel_band_roformer_crowd.yaml",
    },
    1054: {
        "model_name": "viperx_vocals",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://github.com/TRvlvr/model_repo/releases/download/all_public_uvr_models/model_mel_band_roformer_ep_3005_sdr_11.4360.ckpt",
        "conf_url": "https://raw.githubusercontent.com/ZFTurbo/Music-Source-Separation-Training/main/configs/viperx/model_mel_band_roformer_ep_3005_sdr_11.4360.yaml",
    }, 
    1060: {
        "model_name": "unwa_instrumental_v1_plus",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-Inst/resolve/main/inst_v1_plus_test.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-Inst/resolve/main/config_melbandroformer_inst.yaml?download=true",
    }, 
    1061: {
        "model_name": "unwa_instrumental_v1e_plus",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-Inst/resolve/main/inst_v1e_plus.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-Inst/resolve/main/config_melbandroformer_inst.yaml?download=true",
    }, 
    1062: {
        "model_name": "unwa_big_beta_v6x",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-big/resolve/main/big_beta6x.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Mel-Band-Roformer-big/resolve/main/big_beta6x.yaml?download=true",
    }, 
    1063: {
        "model_name": "unwa_kim_ft_v3",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/pcunwa/Kim-Mel-Band-Roformer-FT/resolve/main/kimmel_unwa_ft3_prev.ckpt?download=true",
        "conf_url": "https://huggingface.co/pcunwa/Kim-Mel-Band-Roformer-FT/resolve/main/config_kimmel_unwa_ft.yaml?download=true",
    },
    1201: {
        "model_name": "aname_vocals_fullness",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/Aname-Tommy/MelBandRoformers/resolve/main/FullnessVocalModel.ckpt?download=true",
        "conf_url": "https://huggingface.co/Aname-Tommy/MelBandRoformers/resolve/main/config.yaml?download=true",
    },
   1202: {
        "model_name": "gaboxr67_instrumental_donotusepls",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/donotusepls.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/MelBandRoformers/resolve/main/melbandroformers/instrumental/inst_gabox.yaml?download=true",
    },
    1220: {
        "model_name": "exp_drums",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/am2460162/msst_failed_failed_test/resolve/main/model_mel_band_roformer_ep_11_sdr_7.6853.ckpt?download=true",
        "conf_url": "https://huggingface.co/am2460162/msst_failed_failed_test/resolve/main/config_drums_musdb18_moises_mel_band_roformer.yaml?download=true",
    },
    1300: {
        "model_name": "mesk_metal_inst_prev",
        "arch": "mel_band_roformer",
        "ckpt_url": "https://huggingface.co/meskvlla33/metal_roformer_preview/resolve/main/metal_roformer_inst_mesk_preview.ckpt?download=true",
        "conf_url": "https://huggingface.co/meskvlla33/metal_roformer_preview/resolve/main/config_inst_metal_roformer_mesk.yaml?download=true",
    },
    250: {
        "model_name": "exp_drums",
        "arch": "bs_roformer",
        "ckpt_url": "https://huggingface.co/am2460162/msst_failed_failed_test/resolve/main/model_drums_bs_roformer_ep_12_sdr_7.2279.ckpt?download=true",
        "conf_url": "https://huggingface.co/am2460162/msst_failed_failed_test/resolve/main/config_4_drums_bs_roformer.yaml?download=true",
    },
    251: {
        "model_name": "exp_bass",
        "arch": "bs_roformer",
        "ckpt_url": "https://huggingface.co/am2460162/msst_failed_failed_test/resolve/main/model_bass_bs_roformer_ep_10_sdr_5.7862.ckpt?download=true",
        "conf_url": "https://huggingface.co/am2460162/msst_failed_failed_test/resolve/main/config_4_bass_bs_roformer.yaml?download=true",
    },
    201: {
        "model_name": "viperx_vocals_1296",
        "arch": "bs_roformer",
        "ckpt_url": "https://github.com/TRvlvr/model_repo/releases/download/all_public_uvr_models/model_bs_roformer_ep_368_sdr_12.9628.ckpt",
        "conf_url": "https://raw.githubusercontent.com/TRvlvr/application_data/main/mdx_model_data/mdx_c_configs/model_bs_roformer_ep_368_sdr_12.9628.yaml",
    },
    202: {
        "model_name": "viperx_vocals_1297",
        "arch": "bs_roformer",
        "ckpt_url": "https://github.com/TRvlvr/model_repo/releases/download/all_public_uvr_models/model_bs_roformer_ep_317_sdr_12.9755.ckpt",
        "conf_url": "https://raw.githubusercontent.com/ZFTurbo/Music-Source-Separation-Training/main/configs/viperx/model_bs_roformer_ep_317_sdr_12.9755.yaml",
    },
    203: {
        "model_name": "gabox_vocals",
        "arch": "bs_roformer",
        "ckpt_url": "https://huggingface.co/GaboxR67/BSRoformerVocTest/resolve/main/voc_gaboxBSR.ckpt?download=true",
        "conf_url": "https://huggingface.co/GaboxR67/BSRoformerVocTest/resolve/main/voc_gaboxBSroformer.yaml?download=true",
    },
    204: {
        "model_name": "zf_turbo_4_stems",
        "arch": "bs_roformer",
        "ckpt_url": "https://github.com/ZFTurbo/Music-Source-Separation-Training/releases/download/v1.0.12/model_bs_roformer_ep_17_sdr_9.6568.ckpt",
        "conf_url": "https://github.com/ZFTurbo/Music-Source-Separation-Training/releases/download/v1.0.12/config_bs_roformer_384_8_2_485100.yaml",
    },
    205: {
        "model_name": "syh99999_4_stems_ft",
        "arch": "bs_roformer",
        "ckpt_url": "https://huggingface.co/SYH99999/bs_roformer_4stems_ft/resolve/main/bs_roformer_4stems_ft.pth?download=true",
        "conf_url": "https://huggingface.co/SYH99999/bs_roformer_4stems_ft/resolve/main/config.yaml?download=true",
    },
    206: {
        "model_name": "sucial_male_female_146",
        "arch": "bs_roformer",
        "ckpt_url": "https://huggingface.co/Sucial/Chorus_Male_Female_BS_Roformer/resolve/main/model_chorus_bs_roformer_ep_146_sdr_23.8613.ckpt?download=true",
        "conf_url": "https://huggingface.co/Sucial/Chorus_Male_Female_BS_Roformer/resolve/main/config_chorus_male_female_bs_roformer.yaml?download=true",
    },
    207: {
        "model_name": "sucial_male_female_267",
        "arch": "bs_roformer",
        "ckpt_url": "https://huggingface.co/Sucial/Chorus_Male_Female_BS_Roformer/resolve/main/model_chorus_bs_roformer_ep_267_sdr_24.1275.ckpt?download=true",
        "conf_url": "https://huggingface.co/Sucial/Chorus_Male_Female_BS_Roformer/resolve/main/config_chorus_male_female_bs_roformer.yaml?download=true",
    },
    208: {
        "model_name": "aufr33_male_female",
        "arch": "bs_roformer",
        "ckpt_url": "https://huggingface.co/RareSirMix/AIModelRehosting/resolve/main/bs_roformer_male_female_by_aufr33_sdr_7.2889.ckpt",
        "conf_url": "https://huggingface.co/Sucial/Chorus_Male_Female_BS_Roformer/resolve/main/config_chorus_male_female_bs_roformer.yaml",
    },
    209: {
        "model_name": "anvuew_deverb_256_8",
        "arch": "bs_roformer",
        "ckpt_url": "https://huggingface.co/anvuew/deverb_bs_roformer/resolve/main/deverb_bs_roformer_8_256dim_8depth.ckpt?download=true",
        "conf_url": "https://huggingface.co/anvuew/deverb_bs_roformer/resolve/main/deverb_bs_roformer_8_256dim_8depth.yaml?download=true",
    },
    210: {
        "model_name": "anvuew_deverb_384_10",
        "arch": "bs_roformer",
        "ckpt_url": "https://huggingface.co/anvuew/deverb_bs_roformer/resolve/main/deverb_bs_roformer_8_384dim_10depth.ckpt?download=true",
        "conf_url": "https://huggingface.co/anvuew/deverb_bs_roformer/resolve/main/deverb_bs_roformer_8_384dim_10depth.yaml?download=true",
    },

    # MDX23C Models
    300: {
        "model_name": "inst_voc_hq",
        "arch": "mdx23c",
        "ckpt_url": "https://github.com/ZFTurbo/Music-Source-Separation-Training/releases/download/v1.0.0/model_vocals_mdx23c_sdr_10.17.ckpt",
        "conf_url": "https://raw.githubusercontent.com/ZFTurbo/Music-Source-Separation-Training/main/configs/config_vocals_mdx23c.yaml",
    },
    301: {
        "model_name": "aufr33_jarredou_drumsep",
        "arch": "mdx23c",
        "ckpt_url": "https://github.com/jarredou/models/releases/download/aufr33-jarredou_MDX23C_DrumSep_model_v0.1/aufr33-jarredou_DrumSep_model_mdx23c_ep_141_sdr_10.8059.ckpt",
        "conf_url": "https://github.com/jarredou/models/releases/download/aufr33-jarredou_MDX23C_DrumSep_model_v0.1/aufr33-jarredou_DrumSep_model_mdx23c_ep_141_sdr_10.8059.yaml",
    },
    302: {
        "model_name": "aufr33_jarredou_dereverb",
        "arch": "mdx23c",
        "ckpt_url": "https://huggingface.co/jarredou/aufr33_jarredou_MDXv3_DeReverb/resolve/main/dereverb_mdx23c_sdr_6.9096.ckpt",
        "conf_url": "https://huggingface.co/jarredou/aufr33_jarredou_MDXv3_DeReverb/resolve/main/config_dereverb_mdx23c.yaml",
    },
    303: {
        "model_name": "wesleyr36_mid_side",
        "arch": "mdx23c",
        "ckpt_url": "https://github.com/ZFTurbo/Music-Source-Separation-Training/releases/download/v1.0.10/model_mdx23c_ep_271_l1_freq_72.2383.ckpt",
        "conf_url": "https://github.com/ZFTurbo/Music-Source-Separation-Training/releases/download/v1.0.10/config_mdx23c_similarity.yaml",
    },
    304: {
        "model_name": "zf_turbo_4_stems",
        "arch": "mdx23c",
        "ckpt_url": "https://github.com/ZFTurbo/Music-Source-Separation-Training/releases/download/v1.0.1/model_mdx23c_ep_168_sdr_7.0207.ckpt",
        "conf_url": "https://github.com/ZFTurbo/Music-Source-Separation-Training/releases/download/v1.0.1/config_musdb18_mdx23c.yaml",
    },
    350: {
        "model_name": "exp_orch",
        "arch": "mdx23c",
        "ckpt_url": "https://huggingface.co/am2460162/msst_failed_failed_test/resolve/main/model_mdx23c_ep_120_sdr_4.4174.ckpt?download=true",
        "conf_url": "https://huggingface.co/am2460162/msst_failed_failed_test/resolve/main/config_orchestra_mdx23c.yaml?download=true",
    },

    # SCNET Models
    800: {
        "model_name": "zf_turbo_4_stems",
        "arch": "scnet",
        "ckpt_url": "https://github.com/ZFTurbo/Music-Source-Separation-Training/releases/download/v1.0.9/SCNet-large_starrytong_fixed.ckpt",
        "conf_url": "https://github.com/ZFTurbo/Music-Source-Separation-Training/releases/download/v1.0.9/config_musdb18_scnet_large_starrytong.yaml",
    },
    801: {
        "model_name": "starrytong_4_stems_xl",
        "arch": "scnet",
        "ckpt_url": "https://github.com/ZFTurbo/Music-Source-Separation-Training/releases/download/v1.0.13/model_scnet_ep_54_sdr_9.8051.ckpt",
        "conf_url": "https://github.com/ZFTurbo/Music-Source-Separation-Training/releases/download/v1.0.13/config_musdb18_scnet_xl.yaml",
    },
    802: {
        "model_name": "zf_turbo_4_stems_xl",
        "arch": "scnet",
        "ckpt_url": "https://github.com/ZFTurbo/Music-Source-Separation-Training/releases/download/v.1.0.6/scnet_checkpoint_musdb18.ckpt",
        "conf_url": "https://github.com/ZFTurbo/Music-Source-Separation-Training/releases/download/v.1.0.6/config_musdb18_scnet.yaml",
    },
    600: {
        "model_name": "multi_singing_librispeech",
        "arch": "medleyvox",
        "ckpt_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/multi_singing_librispeech/vocals.pth?download=true",
        "conf_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/multi_singing_librispeech/vocals.json?download=true",
    },
    601: {
        "model_name": "multi_singing_librispeech_138",
        "arch": "medleyvox",
        "ckpt_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/multi_singing_librispeech_138/vocals.pth?download=true",
        "conf_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/multi_singing_librispeech_138/vocals.json?download=true",
    },
    602: {
        "model_name": "singing_librispeech_ft_isrnet",
        "arch": "medleyvox",
        "ckpt_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/singing_librispeech_ft_iSRNet/vocals.pth?download=true",
        "conf_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/singing_librispeech_ft_iSRNet/vocals.json?download=true",
    },
    603: {
        "model_name": "singing_librispeech_isrnet",
        "arch": "medleyvox",
        "ckpt_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/singing_librispeech_iSRNet/vocals.pth?download=true",
        "conf_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/singing_librispeech_iSRNet/vocals.json?download=true",
    },
    604: {
        "model_name": "vocal_231",
        "arch": "medleyvox",
        "ckpt_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/vocal%20231/vocals.pth?download=true",
        "conf_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/vocal%20231/vocals.json?download=true",
    },
    605: {
        "model_name": "vocals_135",
        "arch": "medleyvox",
        "ckpt_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/vocals%20135/vocals.pth?download=true",
        "conf_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/vocals%20135/vocals.json?download=true",
    },
    606: {
        "model_name": "vocals_163",
        "arch": "medleyvox",
        "ckpt_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/vocals%20163/vocals.pth?download=true",
        "conf_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/vocals%20163/vocals.json?download=true",
    },
    607: {
        "model_name": "vocals_188",
        "arch": "medleyvox",
        "ckpt_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/vocals%20188/vocals.pth?download=true",
        "conf_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/vocals%20188/vocals.json?download=true",
    },
    608: {
        "model_name": "vocals_200",
        "arch": "medleyvox",
        "ckpt_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/vocals%20200/vocals.pth?download=true",
        "conf_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/vocals%20200/vocals.json?download=true",
    },
    609: {
        "model_name": "vocals_238",
        "arch": "medleyvox",
        "ckpt_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/vocals%20238/vocals.pth?download=true",
        "conf_url": "https://huggingface.co/Cyru5/MedleyVox/resolve/main/vocals%20238/vocals.json?download=true",
    },
    500: {
        "model_name": "1_HP-UVR",
        "arch": "vr_arch",
        "ckpt_url": "1_HP-UVR.pth",
    },
    501: {
        "model_name": "2_HP-UVR",
        "arch": "vr_arch",
        "ckpt_url": "2_HP-UVR.pth",
    },
    502: {
        "model_name": "3_HP-Vocal-UVR",
        "arch": "vr_arch",
        "ckpt_url": "3_HP-Vocal-UVR.pth",
    },
    503: {
        "model_name": "4_HP-Vocal-UVR",
        "arch": "vr_arch",
        "ckpt_url": "4_HP-Vocal-UVR.pth",
    },
    504: {
        "model_name": "5_HP-Karaoke-UVR",
        "arch": "vr_arch",
        "ckpt_url": "5_HP-Karaoke-UVR.pth",
    },
    505: {
        "model_name": "6_HP-Karaoke-UVR",
        "arch": "vr_arch",
        "ckpt_url": "6_HP-Karaoke-UVR.pth",
    },
    506: {
        "model_name": "7_HP2-UVR",
        "arch": "vr_arch",
        "ckpt_url": "7_HP2-UVR.pth",
    },
    507: {
        "model_name": "8_HP2-UVR",
        "arch": "vr_arch",
        "ckpt_url": "8_HP2-UVR.pth",
    },
    508: {
        "model_name": "9_HP2-UVR",
        "arch": "vr_arch",
        "ckpt_url": "9_HP2-UVR.pth",
    },
    509: {
        "model_name": "10_SP-UVR-2B-32000-1",
        "arch": "vr_arch",
        "ckpt_url": "10_SP-UVR-2B-32000-1.pth",
    },
    510: {
        "model_name": "11_SP-UVR-2B-32000-2",
        "arch": "vr_arch",
        "ckpt_url": "11_SP-UVR-2B-32000-2.pth",
    },
    511: {
        "model_name": "12_SP-UVR-3B-44100",
        "arch": "vr_arch",
        "ckpt_url": "12_SP-UVR-3B-44100.pth",
    },
    512: {
        "model_name": "13_SP-UVR-4B-44100-1",
        "arch": "vr_arch",
        "ckpt_url": "13_SP-UVR-4B-44100-1.pth",
    },
    513: {
        "model_name": "14_SP-UVR-4B-44100-2",
        "arch": "vr_arch",
        "ckpt_url": "14_SP-UVR-4B-44100-2.pth",
    },
    514: {
        "model_name": "15_SP-UVR-MID-44100-1",
        "arch": "vr_arch",
        "ckpt_url": "15_SP-UVR-MID-44100-1.pth",
    },
    515: {
        "model_name": "16_SP-UVR-MID-44100-2",
        "arch": "vr_arch",
        "ckpt_url": "16_SP-UVR-MID-44100-2.pth",
    },
    516: {
        "model_name": "17_HP-Wind_Inst-UVR",
        "arch": "vr_arch",
        "ckpt_url": "17_HP-Wind_Inst-UVR.pth",
    },
    517: {
        "model_name": "UVR-De-Echo-Aggressive",
        "arch": "vr_arch",
        "ckpt_url": "UVR-De-Echo-Aggressive.pth",
    },
    518: {
        "model_name": "UVR-De-Echo-Normal",
        "arch": "vr_arch",
        "ckpt_url": "UVR-De-Echo-Normal.pth",
    },
    519: {
        "model_name": "UVR-DeEcho-DeReverb",
        "arch": "vr_arch",
        "ckpt_url": "UVR-DeEcho-DeReverb.pth",
    },
    520: {
        "model_name": "UVR-De-Reverb-aufr33-jarredou",
        "arch": "vr_arch",
        "ckpt_url": "UVR-De-Reverb-aufr33-jarredou.pth",
    },
    521: {
        "model_name": "UVR-DeNoise-Lite",
        "arch": "vr_arch",
        "ckpt_url": "UVR-DeNoise-Lite.pth",
    },
    522: {
        "model_name": "UVR-DeNoise",
        "arch": "vr_arch",
        "ckpt_url": "UVR-DeNoise.pth",
    },
    523: {
        "model_name": "UVR-BVE-4B_SN-44100-1",
        "arch": "vr_arch",
        "ckpt_url": "UVR-BVE-4B_SN-44100-1.pth",
    },
    524: {
        "model_name": "MGM_HIGHEND_v4",
        "arch": "vr_arch",
        "ckpt_url": "MGM_HIGHEND_v4.pth",
    },
    525: {
        "model_name": "MGM_LOWEND_A_v4",
        "arch": "vr_arch",
        "ckpt_url": "MGM_LOWEND_A_v4.pth",
    },
    526: {
        "model_name": "MGM_LOWEND_B_v4",
        "arch": "vr_arch",
        "ckpt_url": "MGM_LOWEND_B_v4.pth",
    },
    527: {
        "model_name": "MGM_MAIN_v4",
        "arch": "vr_arch",
        "ckpt_url": "MGM_MAIN_v4.pth",
    },

    # MDX-NET Models
    400: {
        "model_name": "UVR-MDX-NET-Inst_full_292",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET-Inst_full_292.onnx",
    },
    401: {
        "model_name": "UVR-MDX-NET_Inst_187_beta",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET_Inst_187_beta.onnx",
    },
    402: {
        "model_name": "UVR-MDX-NET_Inst_82_beta",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET_Inst_82_beta.onnx",
    },
    403: {
        "model_name": "UVR-MDX-NET_Inst_90_beta",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET_Inst_90_beta.onnx",
    },
    404: {
        "model_name": "UVR-MDX-NET_Main_340",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET_Main_340.onnx",
    },
    405: {
        "model_name": "UVR-MDX-NET_Main_390",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET_Main_390.onnx",
    },
    406: {
        "model_name": "UVR-MDX-NET_Main_406",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET_Main_406.onnx",
    },
    407: {
        "model_name": "UVR-MDX-NET_Main_427",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET_Main_427.onnx",
    },
    408: {
        "model_name": "UVR-MDX-NET_Main_438",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET_Main_438.onnx",
    },
    409: {
        "model_name": "UVR-MDX-NET-Inst_HQ_1",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET-Inst_HQ_1.onnx",
    },
    410: {
        "model_name": "UVR-MDX-NET-Inst_HQ_2",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET-Inst_HQ_2.onnx",
    },
    411: {
        "model_name": "UVR-MDX-NET-Inst_HQ_3",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET-Inst_HQ_3.onnx",
    },
    412: {
        "model_name": "UVR-MDX-NET-Inst_HQ_4",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET-Inst_HQ_4.onnx",
    },
    413: {
        "model_name": "UVR-MDX-NET-Inst_HQ_5",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET-Inst_HQ_5.onnx",
    },
    414: {
        "model_name": "UVR_MDXNET_Main",
        "arch": "mdx-net",
        "ckpt_url": "UVR_MDXNET_Main.onnx",
    },
    415: {
        "model_name": "UVR-MDX-NET-Inst_Main",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET-Inst_Main.onnx",
    },
    416: {
        "model_name": "UVR_MDXNET_1_9703",
        "arch": "mdx-net",
        "ckpt_url": "UVR_MDXNET_1_9703.onnx",
    },
    417: {
        "model_name": "UVR_MDXNET_2_9682",
        "arch": "mdx-net",
        "ckpt_url": "UVR_MDXNET_2_9682.onnx",
    },
    418: {
        "model_name": "UVR_MDXNET_3_9662",
        "arch": "mdx-net",
        "ckpt_url": "UVR_MDXNET_3_9662.onnx",
    },
    419: {
        "model_name": "UVR-MDX-NET-Inst_1",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET-Inst_1.onnx",
    },
    420: {
        "model_name": "UVR-MDX-NET-Inst_2",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET-Inst_2.onnx",
    },
    421: {
        "model_name": "UVR-MDX-NET-Inst_3",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET-Inst_3.onnx",
    },
    422: {
        "model_name": "UVR_MDXNET_KARA",
        "arch": "mdx-net",
        "ckpt_url": "UVR_MDXNET_KARA.onnx",
    },
    423: {
        "model_name": "UVR_MDXNET_KARA_2",
        "arch": "mdx-net",
        "ckpt_url": "UVR_MDXNET_KARA_2.onnx",
    },
    424: {
        "model_name": "UVR_MDXNET_9482",
        "arch": "mdx-net",
        "ckpt_url": "UVR_MDXNET_9482.onnx",
    },
    425: {
        "model_name": "UVR-MDX-NET-Voc_FT",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET-Voc_FT.onnx",
    },
    426: {
        "model_name": "Kim_Vocal_1",
        "arch": "mdx-net",
        "ckpt_url": "Kim_Vocal_1.onnx",
    },
    427: {
        "model_name": "Kim_Vocal_2",
        "arch": "mdx-net",
        "ckpt_url": "Kim_Vocal_2.onnx",
    },
    428: {
        "model_name": "Kim_Inst",
        "arch": "mdx-net",
        "ckpt_url": "Kim_Inst.onnx",
    },
    429: {
        "model_name": "Reverb_HQ_By_FoxJoy",
        "arch": "mdx-net",
        "ckpt_url": "Reverb_HQ_By_FoxJoy.onnx",
    },
    430: {
        "model_name": "UVR-MDX-NET_Crowd_HQ_1",
        "arch": "mdx-net",
        "ckpt_url": "UVR-MDX-NET_Crowd_HQ_1.onnx",
    },
    431: {
        "model_name": "kuielab_a_vocals",
        "arch": "mdx-net",
        "ckpt_url": "kuielab_a_vocals.onnx",
    },
    432: {
        "model_name": "kuielab_a_other",
        "arch": "mdx-net",
        "ckpt_url": "kuielab_a_other.onnx",
    },
    433: {
        "model_name": "kuielab_a_bass",
        "arch": "mdx-net",
        "ckpt_url": "kuielab_a_bass.onnx",
    },
    434: {
        "model_name": "kuielab_a_drums",
        "arch": "mdx-net",
        "ckpt_url": "kuielab_a_drums.onnx",
    },
    435: {
        "model_name": "kuielab_b_vocals",
        "arch": "mdx-net",
        "ckpt_url": "kuielab_b_vocals.onnx",
    },
    436: {
        "model_name": "kuielab_b_other",
        "arch": "mdx-net",
        "ckpt_url": "kuielab_b_other.onnx",
    },
    437: {
        "model_name": "kuielab_b_bass",
        "arch": "mdx-net",
        "ckpt_url": "kuielab_b_bass.onnx",
    },
    438: {
        "model_name": "kuielab_b_drums",
        "arch": "mdx-net",
        "ckpt_url": "kuielab_b_drums.onnx",
    },

    # Demucs Models
    90: {
        "model_name": "htdemucs_ft",
        "arch": "demucs",
        "ckpt_url": "htdemucs_ft.yaml",
    },
    91: {
        "model_name": "htdemucs",
        "arch": "demucs",
        "ckpt_url": "htdemucs.yaml",
    },
    92: {
        "model_name": "hdemucs_mmi",
        "arch": "demucs",
        "ckpt_url": "hdemucs_mmi.yaml",
    },
    93: {
        "model_name": "htdemucs_6s",
        "arch": "demucs",
        "ckpt_url": "htdemucs_6s.yaml",
    },
}

def get_model_config(model_code):
    return MODELS_CONFIG.get(model_code, {})
